### ISSUE TITLE
Vertaispalaute

### ISSUE THREAD

**Issue by apndx** [jolampi/ultira-ai-toe#1]
ti 8.10.2018 21:30 tätä versiota katsoin ilman testejä
pe 8.10.2018 21:30 testit mukaan + uusi versio dictionarystä

Minulla oli hieman haasteita projektin avaamisessa ja aluksi myös ymmärtämisessä. Kun latasin projektin Gitistä, en saanut sitä suoraan auki NetBeansin kautta (NetBeans ei tunnistanut projektikansiota oikean muotoiseksi). Projektin kuvauksessa voisikin ehkä olla jonkun sortin asennusohje, tai maininta millä IDE:llä tms. koodia on työstetty.

Pelin idea oli selitetty mukavasti auki dokumentaatiossa. Aihe oli kuitenkin itselle sen verran vieras, että olisin kaivannut rautalankaohjetta siihen, miten human playeriä käytetään sekä vinkkiä mitä pelin palauttamat numerolistat tarkoittavat jos molemmat pelaajat ovat ai-pelaajia.

Board -luokka on hyvin kommentoitu ja testattu, samaa vaan lisää muuallekin :). Myös muut testit näyttivät hyviltä ja menivät myös läpi.

Pakkausten ja luokkien rakenne näyttää hyvältä, myös muuttujat on nimetty kuvaavasti. Koodi näyttää myös rakenteltaan selkeältä, ja metodit ovat napakoita.

Lueskeltuani koodia sain vihdoin pelinkin alulle, sain myös pelin aika pian kaatumaan testaamalla syötteenä numeroa "10".

Pelin seuraamista voisi helpottaa, jos edellinen siirto näkyisi jotenkin erikseen tai korostettuna, niin että sitä ei tarvitsisi etsiä pelilaudoilta. Vaikka yleensä onkin loogista, minne siirto tulee, niin silti silmä harhailee, varsinkin kun pelilaudat alkavat täyttyä :). Ja välillä tosiaan ei tiedä, mikä lauta seuraavaksi pelataan jos on sattunut jonkin laudan voittamaan.

Yhden pelin jälkeen ei vielä selvinnyt se, miten ihmispelaaja valitsee pelattavan laudan, kun AI:n siirto viittaa pelaamaan seuraavaksi jo voitettuun peliin.

Kovin pitkään en pelannut, mutta tekoäly vaikutti voitontahtoiselta :)

Hauska aihe projektille, tsemppiä pelin viimeistelyyn!

**Comment by jolampi** [comment]
Kiitos palautteesta!
Olen sen koulukunnan kannalla, ettei IDEn tulisi olla mitenkään tekemissä lähdekoodin kanssa. Netbeans-valmiiksi projektiksi tunnistavat tiedostot siis jäivät gitignoreen. Tämä ei valitettavasti palvele hyvin vertaisarvioinnin tavoitteita, joten jonkinlaista ohjeistusta olisi varmaan pitänyt miettiä. Fokus vain on valitettavasti ollut aivan muualla kuin ns. loppukäyttäjäkokemuksessa, minkä takia pelitilanteen esittämispuoli on hieman kärsinyt. On tuota tullut itsekin välillä raavittua päätä omissa testauksissa.
Kiitos tuon kaatumisen havaitsemisesta. Numeroiden kelpaavuuden tarkistamiseen on näemmä päässyt lipsahtamaan pari aukkoa joidenkin muutosten myötä.
Seuraavan laudan valitseminen tosiaan tapahtuu syöttämällä kaksi lukua peräkkäin; ensin valitaan lauta ja sitten siirto.
